// ============================================================
// SISTEMA DE PERMISSÕES POR ROLE (MATRIZ OFICIAL RBAC)
// Tk Gestão e Tecnologia • Controle de Acesso e Hierarquia
// ============================================================

import type { UserRole, RolePermissions } from '../types/restaurant.types';

// Mapa completo de permissões granulares por role
const ROLE_PERMISSIONS: Record<UserRole, RolePermissions> = {
  // 1. DONOS (Acesso 100) — Rogério & Sidney: Visão estratégica completa
  DONO: {
    canViewExecutiveDashboard: true,
    canViewFinancialDRE: true,
    canViewCashFlow: true,
    canViewSales: true,
    canViewDrinksSalesOnly: false,
    canViewFullStock: true,
    canViewKitchenStock: true,
    canViewBarStock: true,
    canCountStock: true,
    canSuperviseAndSignInventory: true,
    canAuditInventory: true,
    canRequestPurchase: true,
    canApprovePurchase: true,
    canAuditPurchase: true,
    canManageRecipes: true,
    canManageAllStaff: true,
    canManageKitchenStaff: true,
    canManageRosters: true,
    canManageKitchenRoster: true,
    canViewOwnRosterOnly: false,
    canManageAllChecklists: true,
    canManageKitchenChecklists: true,
    canManageBarChecklists: true,
    canManageCleaningChecklists: true,
    canViewAuditTrail: true,
    canSignAudits: true,
    canManageUsers: true,
    canManageRestaurants: true,
    canAccessAdmin: true,
    canManageSystemSettings: true,

    // Compatibilidade Legada
    canAddProducts: true,
    canImportSales: true,
    canRegisterWriteOffs: true,
    canApproveWriteOffs: true,
    canTransferStock: true,
    canRequestRecount: true,
    canViewReports: true,
    canViewDashboard: true,
    canViewFullDashboard: true,
    canViewAuditCalendar: true,
    canCreateAudit: true,
    canViewStaff: true,
    canManageStaff: true,
    canViewMarketing: true,
    canViewCopilot: true,
  },

  PROPRIETARIO: {
    canViewExecutiveDashboard: true,
    canViewFinancialDRE: true,
    canViewCashFlow: true,
    canViewSales: true,
    canViewDrinksSalesOnly: false,
    canViewFullStock: true,
    canViewKitchenStock: true,
    canViewBarStock: true,
    canCountStock: true,
    canSuperviseAndSignInventory: true,
    canAuditInventory: true,
    canRequestPurchase: true,
    canApprovePurchase: true,
    canAuditPurchase: true,
    canManageRecipes: true,
    canManageAllStaff: true,
    canManageKitchenStaff: true,
    canManageRosters: true,
    canManageKitchenRoster: true,
    canViewOwnRosterOnly: false,
    canManageAllChecklists: true,
    canManageKitchenChecklists: true,
    canManageBarChecklists: true,
    canManageCleaningChecklists: true,
    canViewAuditTrail: true,
    canSignAudits: true,
    canManageUsers: true,
    canManageRestaurants: true,
    canAccessAdmin: true,
    canManageSystemSettings: true,

    canAddProducts: true,
    canImportSales: true,
    canRegisterWriteOffs: true,
    canApproveWriteOffs: true,
    canTransferStock: true,
    canRequestRecount: true,
    canViewReports: true,
    canViewDashboard: true,
    canViewFullDashboard: true,
    canViewAuditCalendar: true,
    canCreateAudit: true,
    canViewStaff: true,
    canManageStaff: true,
    canViewMarketing: true,
    canViewCopilot: true,
  },

  // 2. GERENTE (Acesso 90) — Ivan: Auditor operacional da unidade
  GERENTE: {
    canViewExecutiveDashboard: true,
    canViewFinancialDRE: true,
    canViewCashFlow: true,
    canViewSales: true,
    canViewDrinksSalesOnly: false,
    canViewFullStock: true,
    canViewKitchenStock: true,
    canViewBarStock: true,
    canCountStock: true,
    canSuperviseAndSignInventory: false,
    canAuditInventory: true, // Audita e dá feedback
    canRequestPurchase: true,
    canApprovePurchase: false, // A Supervisora é quem aprova; Gerente audita
    canAuditPurchase: true,   // Audita compras e dá feedback
    canManageRecipes: true,
    canManageAllStaff: true,
    canManageKitchenStaff: true,
    canManageRosters: true,
    canManageKitchenRoster: true,
    canViewOwnRosterOnly: false,
    canManageAllChecklists: true,
    canManageKitchenChecklists: true,
    canManageBarChecklists: true,
    canManageCleaningChecklists: true,
    canViewAuditTrail: true,
    canSignAudits: true,
    canManageUsers: false,
    canManageRestaurants: false,
    canAccessAdmin: false,
    canManageSystemSettings: false, // Somente parâmetros operacionais

    canAddProducts: true,
    canImportSales: true,
    canRegisterWriteOffs: true,
    canApproveWriteOffs: true,
    canTransferStock: true,
    canRequestRecount: true,
    canViewReports: true,
    canViewDashboard: true,
    canViewFullDashboard: true,
    canViewAuditCalendar: true,
    canCreateAudit: true,
    canViewStaff: true,
    canManageStaff: true,
    canViewMarketing: true,
    canViewCopilot: true,
  },

  // Master Admin — Pabricio: Criador e Administrador Global
  GERENTE_TREINAMENTO: {
    canViewExecutiveDashboard: true,
    canViewFinancialDRE: true,
    canViewCashFlow: true,
    canViewSales: true,
    canViewDrinksSalesOnly: false,
    canViewFullStock: true,
    canViewKitchenStock: true,
    canViewBarStock: true,
    canCountStock: true,
    canSuperviseAndSignInventory: true,
    canAuditInventory: true,
    canRequestPurchase: true,
    canApprovePurchase: true,
    canAuditPurchase: true,
    canManageRecipes: true,
    canManageAllStaff: true,
    canManageKitchenStaff: true,
    canManageRosters: true,
    canManageKitchenRoster: true,
    canViewOwnRosterOnly: false,
    canManageAllChecklists: true,
    canManageKitchenChecklists: true,
    canManageBarChecklists: true,
    canManageCleaningChecklists: true,
    canViewAuditTrail: true,
    canSignAudits: true,
    canManageUsers: true,
    canManageRestaurants: true,
    canAccessAdmin: true,
    canManageSystemSettings: true,

    canAddProducts: true,
    canImportSales: true,
    canRegisterWriteOffs: true,
    canApproveWriteOffs: true,
    canTransferStock: true,
    canRequestRecount: true,
    canViewReports: true,
    canViewDashboard: true,
    canViewFullDashboard: true,
    canViewAuditCalendar: true,
    canCreateAudit: true,
    canViewStaff: true,
    canManageStaff: true,
    canViewMarketing: true,
    canViewCopilot: true,
  },

  // 3. SUPERVISORA (Acesso 75) — Patricia: Gestora administrativa da operação
  // NUNCA pode acessar: DRE, Lucro Líquido, Salários, Dados bancários, Permissões
  SUPERVISOR: {
    canViewExecutiveDashboard: false,
    canViewFinancialDRE: false,
    canViewCashFlow: false,
    canViewSales: false,
    canViewDrinksSalesOnly: false,
    canViewFullStock: false, // Contagem cega
    canViewKitchenStock: true, // 👁️ Visualiza e confere
    canViewBarStock: true,     // 👁️ Visualiza e confere
    canCountStock: true,
    canSuperviseAndSignInventory: true, // ASSINA DIGITALMENTE E BLOQUEIA
    canAuditInventory: false,
    canRequestPurchase: false,
    canApprovePurchase: true, // APROVA TODAS AS SOLICITAÇÕES COM ASSINATURA ELETRÔNICA
    canAuditPurchase: false,
    canManageRecipes: false,
    canManageAllStaff: true,
    canManageKitchenStaff: true,
    canManageRosters: true,
    canManageKitchenRoster: true,
    canViewOwnRosterOnly: false,
    canManageAllChecklists: true,
    canManageKitchenChecklists: true,
    canManageBarChecklists: true,
    canManageCleaningChecklists: true,
    canViewAuditTrail: true, // 👁️
    canSignAudits: true,
    canManageUsers: false,
    canManageRestaurants: false,
    canAccessAdmin: false,
    canManageSystemSettings: false,

    canAddProducts: true,
    canImportSales: true,
    canRegisterWriteOffs: true,
    canApproveWriteOffs: false,
    canTransferStock: false,
    canRequestRecount: true,
    canViewReports: false,
    canViewDashboard: true,
    canViewFullDashboard: false,
    canViewAuditCalendar: true,
    canCreateAudit: false,
    canViewStaff: true,
    canManageStaff: true,
    canViewMarketing: false,
    canViewCopilot: true,
  },

  SUPERVISORA: {
    canViewExecutiveDashboard: false,
    canViewFinancialDRE: false,
    canViewCashFlow: false,
    canViewSales: false,
    canViewDrinksSalesOnly: false,
    canViewFullStock: false,
    canViewKitchenStock: true,
    canViewBarStock: true,
    canCountStock: true,
    canSuperviseAndSignInventory: true,
    canAuditInventory: false,
    canRequestPurchase: false,
    canApprovePurchase: true,
    canAuditPurchase: false,
    canManageRecipes: false,
    canManageAllStaff: true,
    canManageKitchenStaff: true,
    canManageRosters: true,
    canManageKitchenRoster: true,
    canViewOwnRosterOnly: false,
    canManageAllChecklists: true,
    canManageKitchenChecklists: true,
    canManageBarChecklists: true,
    canManageCleaningChecklists: true,
    canViewAuditTrail: true,
    canSignAudits: true,
    canManageUsers: false,
    canManageRestaurants: false,
    canAccessAdmin: false,
    canManageSystemSettings: false,

    canAddProducts: true,
    canImportSales: true,
    canRegisterWriteOffs: true,
    canApproveWriteOffs: false,
    canTransferStock: false,
    canRequestRecount: true,
    canViewReports: false,
    canViewDashboard: true,
    canViewFullDashboard: false,
    canViewAuditCalendar: true,
    canCreateAudit: false,
    canViewStaff: true,
    canManageStaff: true,
    canViewMarketing: false,
    canViewCopilot: true,
  },

  // 4. CHEFE DE COZINHA (Acesso 60) — Mádio: Responsável técnico
  CHEFE_COZINHA: {
    canViewExecutiveDashboard: false,
    canViewFinancialDRE: false,
    canViewCashFlow: false,
    canViewSales: false,
    canViewDrinksSalesOnly: false,
    canViewFullStock: false,
    canViewKitchenStock: true, // Estoque da cozinha e câmara fria
    canViewBarStock: false,
    canCountStock: true,
    canSuperviseAndSignInventory: false,
    canAuditInventory: false,
    canRequestPurchase: true, // SOLICITA INSUMOS
    canApprovePurchase: false,
    canAuditPurchase: false,
    canManageRecipes: true, // Fichas técnicas da cozinha
    canManageAllStaff: false,
    canManageKitchenStaff: true, // Equipe da cozinha
    canManageRosters: false,
    canManageKitchenRoster: true, // Escala da cozinha
    canViewOwnRosterOnly: false,
    canManageAllChecklists: false,
    canManageKitchenChecklists: true, // Checklists da cozinha
    canManageBarChecklists: false,
    canManageCleaningChecklists: false,
    canViewAuditTrail: false,
    canSignAudits: false,
    canManageUsers: false,
    canManageRestaurants: false,
    canAccessAdmin: false,
    canManageSystemSettings: false,

    canAddProducts: true,
    canImportSales: false,
    canRegisterWriteOffs: true,
    canApproveWriteOffs: false,
    canTransferStock: false,
    canRequestRecount: false,
    canViewReports: false,
    canViewDashboard: true,
    canViewFullDashboard: false,
    canViewAuditCalendar: true,
    canCreateAudit: false,
    canViewStaff: true,
    canManageStaff: false,
    canViewMarketing: false,
    canViewCopilot: true,
  },

  // 5. SUBCHEFE (Acesso 60) — Esmael: Operação diária da cozinha
  // Diferenças: Não altera ficha técnica, não finaliza inventário, não aprova pedidos
  SUB_CHEFE_COZINHA: {
    canViewExecutiveDashboard: false,
    canViewFinancialDRE: false,
    canViewCashFlow: false,
    canViewSales: false,
    canViewDrinksSalesOnly: false,
    canViewFullStock: false,
    canViewKitchenStock: true,
    canViewBarStock: false,
    canCountStock: true,
    canSuperviseAndSignInventory: false,
    canAuditInventory: false,
    canRequestPurchase: true,
    canApprovePurchase: false,
    canAuditPurchase: false,
    canManageRecipes: false, // ❌ NÃO altera ficha técnica
    canManageAllStaff: false,
    canManageKitchenStaff: true,
    canManageRosters: false,
    canManageKitchenRoster: true,
    canViewOwnRosterOnly: false,
    canManageAllChecklists: false,
    canManageKitchenChecklists: true,
    canManageBarChecklists: false,
    canManageCleaningChecklists: false,
    canViewAuditTrail: false,
    canSignAudits: false,
    canManageUsers: false,
    canManageRestaurants: false,
    canAccessAdmin: false,
    canManageSystemSettings: false,

    canAddProducts: true,
    canImportSales: false,
    canRegisterWriteOffs: true,
    canApproveWriteOffs: false,
    canTransferStock: false,
    canRequestRecount: false,
    canViewReports: false,
    canViewDashboard: true,
    canViewFullDashboard: false,
    canViewAuditCalendar: true,
    canCreateAudit: false,
    canViewStaff: true,
    canManageStaff: false,
    canViewMarketing: false,
    canViewCopilot: true,
  },

  SUBCHEFE: {
    canViewExecutiveDashboard: false,
    canViewFinancialDRE: false,
    canViewCashFlow: false,
    canViewSales: false,
    canViewDrinksSalesOnly: false,
    canViewFullStock: false,
    canViewKitchenStock: true,
    canViewBarStock: false,
    canCountStock: true,
    canSuperviseAndSignInventory: false,
    canAuditInventory: false,
    canRequestPurchase: true,
    canApprovePurchase: false,
    canAuditPurchase: false,
    canManageRecipes: false,
    canManageAllStaff: false,
    canManageKitchenStaff: true,
    canManageRosters: false,
    canManageKitchenRoster: true,
    canViewOwnRosterOnly: false,
    canManageAllChecklists: false,
    canManageKitchenChecklists: true,
    canManageBarChecklists: false,
    canManageCleaningChecklists: false,
    canViewAuditTrail: false,
    canSignAudits: false,
    canManageUsers: false,
    canManageRestaurants: false,
    canAccessAdmin: false,
    canManageSystemSettings: false,

    canAddProducts: true,
    canImportSales: false,
    canRegisterWriteOffs: true,
    canApproveWriteOffs: false,
    canTransferStock: false,
    canRequestRecount: false,
    canViewReports: false,
    canViewDashboard: true,
    canViewFullDashboard: false,
    canViewAuditCalendar: true,
    canCreateAudit: false,
    canViewStaff: true,
    canManageStaff: false,
    canViewMarketing: false,
    canViewCopilot: true,
  },

  // 6. BARTENDER (Acesso 40) — Pedro: Perfil totalmente isolado
  // NUNCA pode acessar: Pratos, Cozinha, Financeiro, Caixa, Salários, Escalas de outros setores
  CHEFE_BAR: {
    canViewExecutiveDashboard: false,
    canViewFinancialDRE: false,
    canViewCashFlow: false,
    canViewSales: false,
    canViewDrinksSalesOnly: true, // Vendas de bebidas apenas
    canViewFullStock: false,
    canViewKitchenStock: false,
    canViewBarStock: true, // Estoque exclusivo de bebidas
    canCountStock: true,
    canSuperviseAndSignInventory: false,
    canAuditInventory: false,
    canRequestPurchase: true, // SOLICITA BEBIDAS
    canApprovePurchase: false,
    canAuditPurchase: false,
    canManageRecipes: true, // Fichas de drinks
    canManageAllStaff: false,
    canManageKitchenStaff: false,
    canManageRosters: false,
    canManageKitchenRoster: false,
    canViewOwnRosterOnly: true, // Próprio
    canManageAllChecklists: false,
    canManageKitchenChecklists: false,
    canManageBarChecklists: true, // Checklists do bar
    canManageCleaningChecklists: false,
    canViewAuditTrail: false,
    canSignAudits: false,
    canManageUsers: false,
    canManageRestaurants: false,
    canAccessAdmin: false,
    canManageSystemSettings: false,

    canAddProducts: true,
    canImportSales: false,
    canRegisterWriteOffs: true,
    canApproveWriteOffs: false,
    canTransferStock: false,
    canRequestRecount: false,
    canViewReports: false,
    canViewDashboard: true,
    canViewFullDashboard: false,
    canViewAuditCalendar: false,
    canCreateAudit: false,
    canViewStaff: false,
    canManageStaff: false,
    canViewMarketing: false,
    canViewCopilot: true,
  },

  BARTENDER: {
    canViewExecutiveDashboard: false,
    canViewFinancialDRE: false,
    canViewCashFlow: false,
    canViewSales: false,
    canViewDrinksSalesOnly: true,
    canViewFullStock: false,
    canViewKitchenStock: false,
    canViewBarStock: true,
    canCountStock: true,
    canSuperviseAndSignInventory: false,
    canAuditInventory: false,
    canRequestPurchase: true,
    canApprovePurchase: false,
    canAuditPurchase: false,
    canManageRecipes: true,
    canManageAllStaff: false,
    canManageKitchenStaff: false,
    canManageRosters: false,
    canManageKitchenRoster: false,
    canViewOwnRosterOnly: true,
    canManageAllChecklists: false,
    canManageKitchenChecklists: false,
    canManageBarChecklists: true,
    canManageCleaningChecklists: false,
    canViewAuditTrail: false,
    canSignAudits: false,
    canManageUsers: false,
    canManageRestaurants: false,
    canAccessAdmin: false,
    canManageSystemSettings: false,

    canAddProducts: true,
    canImportSales: false,
    canRegisterWriteOffs: true,
    canApproveWriteOffs: false,
    canTransferStock: false,
    canRequestRecount: false,
    canViewReports: false,
    canViewDashboard: true,
    canViewFullDashboard: false,
    canViewAuditCalendar: false,
    canCreateAudit: false,
    canViewStaff: false,
    canManageStaff: false,
    canViewMarketing: false,
    canViewCopilot: true,
  },

  // 7. ASG (Acesso 30) — Ambiente simplificado
  // Sem acesso a estoque ou vendas
  ASG: {
    canViewExecutiveDashboard: false,
    canViewFinancialDRE: false,
    canViewCashFlow: false,
    canViewSales: false,
    canViewDrinksSalesOnly: false,
    canViewFullStock: false,
    canViewKitchenStock: false,
    canViewBarStock: false,
    canCountStock: true, // Insumos de limpeza e descartáveis
    canSuperviseAndSignInventory: false,
    canAuditInventory: false,
    canRequestPurchase: false,
    canApprovePurchase: false,
    canAuditPurchase: false,
    canManageRecipes: false,
    canManageAllStaff: false,
    canManageKitchenStaff: false,
    canManageRosters: false,
    canManageKitchenRoster: false,
    canViewOwnRosterOnly: true, // Próprio
    canManageAllChecklists: false,
    canManageKitchenChecklists: false,
    canManageBarChecklists: false,
    canManageCleaningChecklists: true, // Limpeza e higienização
    canViewAuditTrail: false,
    canSignAudits: false,
    canManageUsers: false,
    canManageRestaurants: false,
    canAccessAdmin: false,
    canManageSystemSettings: false,

    canAddProducts: false,
    canImportSales: false,
    canRegisterWriteOffs: false,
    canApproveWriteOffs: false,
    canTransferStock: false,
    canRequestRecount: false,
    canViewReports: false,
    canViewDashboard: true,
    canViewFullDashboard: false,
    canViewAuditCalendar: false,
    canCreateAudit: false,
    canViewStaff: false,
    canManageStaff: false,
    canViewMarketing: false,
    canViewCopilot: true,
  },

  // Comissária (Acesso 40)
  COMISSARIA: {
    canViewExecutiveDashboard: false,
    canViewFinancialDRE: false,
    canViewCashFlow: false,
    canViewSales: false,
    canViewDrinksSalesOnly: false,
    canViewFullStock: false,
    canViewKitchenStock: false,
    canViewBarStock: true,
    canCountStock: true,
    canSuperviseAndSignInventory: false,
    canAuditInventory: false,
    canRequestPurchase: true,
    canApprovePurchase: false,
    canAuditPurchase: false,
    canManageRecipes: false,
    canManageAllStaff: false,
    canManageKitchenStaff: false,
    canManageRosters: false,
    canManageKitchenRoster: false,
    canViewOwnRosterOnly: true,
    canManageAllChecklists: false,
    canManageKitchenChecklists: false,
    canManageBarChecklists: false,
    canManageCleaningChecklists: false,
    canViewAuditTrail: false,
    canSignAudits: false,
    canManageUsers: false,
    canManageRestaurants: false,
    canAccessAdmin: false,
    canManageSystemSettings: false,

    canAddProducts: true,
    canImportSales: false,
    canRegisterWriteOffs: true,
    canApproveWriteOffs: false,
    canTransferStock: false,
    canRequestRecount: false,
    canViewReports: false,
    canViewDashboard: true,
    canViewFullDashboard: false,
    canViewAuditCalendar: false,
    canCreateAudit: false,
    canViewStaff: false,
    canManageStaff: false,
    canViewMarketing: false,
    canViewCopilot: true,
  },

  // Caixa (Acesso 40)
  CAIXA: {
    canViewExecutiveDashboard: false,
    canViewFinancialDRE: false,
    canViewCashFlow: false,
    canViewSales: false,
    canViewDrinksSalesOnly: false,
    canViewFullStock: false,
    canViewKitchenStock: false,
    canViewBarStock: false,
    canCountStock: true,
    canSuperviseAndSignInventory: false,
    canAuditInventory: false,
    canRequestPurchase: true,
    canApprovePurchase: false,
    canAuditPurchase: false,
    canManageRecipes: false,
    canManageAllStaff: false,
    canManageKitchenStaff: false,
    canManageRosters: false,
    canManageKitchenRoster: false,
    canViewOwnRosterOnly: true,
    canManageAllChecklists: false,
    canManageKitchenChecklists: false,
    canManageBarChecklists: false,
    canManageCleaningChecklists: false,
    canViewAuditTrail: false,
    canSignAudits: false,
    canManageUsers: false,
    canManageRestaurants: false,
    canAccessAdmin: false,
    canManageSystemSettings: false,

    canAddProducts: true,
    canImportSales: false,
    canRegisterWriteOffs: true,
    canApproveWriteOffs: false,
    canTransferStock: false,
    canRequestRecount: false,
    canViewReports: false,
    canViewDashboard: true,
    canViewFullDashboard: false,
    canViewAuditCalendar: false,
    canCreateAudit: false,
    canViewStaff: false,
    canManageStaff: false,
    canViewMarketing: false,
    canViewCopilot: true,
  },

  // Operador
  OPERADOR: {
    canViewExecutiveDashboard: false,
    canViewFinancialDRE: false,
    canViewCashFlow: false,
    canViewSales: false,
    canViewDrinksSalesOnly: false,
    canViewFullStock: false,
    canViewKitchenStock: false,
    canViewBarStock: false,
    canCountStock: false,
    canSuperviseAndSignInventory: false,
    canAuditInventory: false,
    canRequestPurchase: false,
    canApprovePurchase: false,
    canAuditPurchase: false,
    canManageRecipes: false,
    canManageAllStaff: false,
    canManageKitchenStaff: false,
    canManageRosters: false,
    canManageKitchenRoster: false,
    canViewOwnRosterOnly: true,
    canManageAllChecklists: false,
    canManageKitchenChecklists: false,
    canManageBarChecklists: false,
    canManageCleaningChecklists: false,
    canViewAuditTrail: false,
    canSignAudits: false,
    canManageUsers: false,
    canManageRestaurants: false,
    canAccessAdmin: false,
    canManageSystemSettings: false,

    canAddProducts: false,
    canImportSales: false,
    canRegisterWriteOffs: false,
    canApproveWriteOffs: false,
    canTransferStock: false,
    canRequestRecount: false,
    canViewReports: false,
    canViewDashboard: true,
    canViewFullDashboard: false,
    canViewAuditCalendar: false,
    canCreateAudit: false,
    canViewStaff: false,
    canManageStaff: false,
    canViewMarketing: false,
    canViewCopilot: false,
  },

  // 8. CHEFE DE FILA / HOSTESS (Acesso 40)
  CHEFE_FILA: {
    canViewExecutiveDashboard: false,
    canViewFinancialDRE: false,
    canViewCashFlow: false,
    canViewSales: false,
    canViewDrinksSalesOnly: false,
    canViewFullStock: false,
    canViewKitchenStock: false,
    canViewBarStock: false,
    canCountStock: false,
    canSuperviseAndSignInventory: false,
    canAuditInventory: false,
    canRequestPurchase: false,
    canApprovePurchase: false,
    canAuditPurchase: false,
    canManageRecipes: false,
    canManageAllStaff: false,
    canManageKitchenStaff: false,
    canManageRosters: false,
    canManageKitchenRoster: false,
    canViewOwnRosterOnly: true,
    canManageAllChecklists: false,
    canManageKitchenChecklists: false,
    canManageBarChecklists: false,
    canManageCleaningChecklists: false,
    canViewAuditTrail: false,
    canSignAudits: false,
    canManageUsers: false,
    canManageRestaurants: false,
    canAccessAdmin: false,
    canManageSystemSettings: false,

    canAddProducts: false,
    canImportSales: false,
    canRegisterWriteOffs: false,
    canApproveWriteOffs: false,
    canTransferStock: false,
    canRequestRecount: false,
    canViewReports: false,
    canViewDashboard: true,
    canViewFullDashboard: false,
    canViewAuditCalendar: false,
    canCreateAudit: false,
    canViewStaff: false,
    canManageStaff: false,
    canViewMarketing: false,
    canViewCopilot: false,
  },
};

/**
 * Retorna o mapa de permissões para uma role específica
 */
export function getPermissions(role: UserRole): RolePermissions {
  return ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS.OPERADOR;
}

/**
 * Verifica se uma role possui uma permissão específica
 */
export function hasPermission(role: UserRole, permission: keyof RolePermissions): boolean {
  return getPermissions(role)[permission];
}
